=== savioa/ipb-documentos/documento.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="https://savioa.github.io/ipb-documentos"
    xmlns="https://savioa.github.io/ipb-documentos"
    elementFormDefault="qualified">
    <xsd:element name="documento">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="preambulo" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="texto" type="Texto" />
                            <xsd:element name="anotacoes" type="Anotacoes" minOccurs="0" maxOccurs="unbounded" />
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="capitulo" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="secao" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="artigo" maxOccurs="unbounded">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="caput" maxOccurs="1">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="texto" type="Texto" maxOccurs="unbounded" />
                                                                <xsd:element name="anotacoes" type="Anotacoes" minOccurs="0" maxOccurs="unbounded" />
                                                                <xsd:element name="alineas" type="Alineas" minOccurs="0" maxOccurs="1" />
                                                                <xsd:element name="incisos" type="Incisos" minOccurs="0" maxOccurs="1" />
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="paragrafo" minOccurs="0" maxOccurs="unbounded">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="texto" type="Texto" maxOccurs="unbounded" />
                                                                <xsd:element name="anotacoes" type="Anotacoes" minOccurs="0" maxOccurs="unbounded" />
                                                                <xsd:element name="alineas" type="Alineas" minOccurs="0" maxOccurs="1" />
                                                                <xsd:element name="incisos" type="Incisos" minOccurs="0" maxOccurs="1" />
                                                            </xsd:sequence>
                                                            <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                                <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                    <xsd:attribute name="id" type="xsd:positiveInteger" use="required" />
                                    <xsd:attribute name="titulo" type="xsd:string" use="optional" />
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                        <xsd:attribute name="id" use="required">
                            <xsd:simpleType>
                                <xsd:restriction base="xsd:string">
                                    <xsd:pattern value="\d{1,2}" />
                                    <xsd:pattern value="dg|dt" />
                                </xsd:restriction>
                            </xsd:simpleType>
                        </xsd:attribute>
                        <xsd:attribute name="titulo" type="xsd:string" use="required" />
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
            <xsd:attribute name="titulo" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="ValorTexto" mixed="true">
        <xsd:sequence>
            <xsd:element name="ref" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType mixed="true">
                    <xsd:attribute name="doc" use="required">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="ci">
                                    <xsd:annotation>
                                        <xsd:documentation>Constituição</xsd:documentation>
                                    </xsd:annotation>
                                </xsd:enumeration>
                                <xsd:enumeration value="es">
                                    <xsd:annotation>
                                        <xsd:documentation>Estatutos</xsd:documentation>
                                    </xsd:annotation>
                                </xsd:enumeration>
                                <xsd:enumeration value="pl">
                                    <xsd:annotation>
                                        <xsd:documentation>Princípios de Liturgia</xsd:documentation>
                                    </xsd:annotation>
                                </xsd:enumeration>
                                <xsd:enumeration value="cd">
                                    <xsd:annotation>
                                        <xsd:documentation>Código de Disciplina</xsd:documentation>
                                    </xsd:annotation>
                                </xsd:enumeration>
                                <xsd:enumeration value="meil">
                                    <xsd:annotation>
                                        <xsd:documentation>Modelo de Estatuto para Igreja Local</xsd:documentation>
                                    </xsd:annotation>
                                </xsd:enumeration>
                                <xsd:enumeration value="mep">
                                    <xsd:annotation>
                                        <xsd:documentation>Modelo de Estatuto para o Presbitério</xsd:documentation>
                                    </xsd:annotation>
                                </xsd:enumeration>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:attribute>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="pos" minOccurs="0" maxOccurs="unbounded">
                <xsd:complexType mixed="true">
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Texto">
        <xsd:complexContent>
            <xsd:extension base="ValorTexto">
                <xsd:attribute name="ordem" type="xsd:positiveInteger" use="optional" />
                <xsd:attribute name="instrumento" type="xsd:string" use="optional" />
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="Alineas">
        <xsd:sequence>
            <xsd:element name="alinea" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="texto" type="Texto" maxOccurs="unbounded" />
                        <xsd:element name="anotacoes" type="Anotacoes" minOccurs="0" maxOccurs="unbounded" />
                    </xsd:sequence>
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Incisos">
        <xsd:sequence>
            <xsd:element name="inciso" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="texto" type="Texto" maxOccurs="unbounded" />
                        <xsd:element name="alineas" type="Alineas" minOccurs="0" maxOccurs="1" />
                    </xsd:sequence>
                    <xsd:attribute name="id" type="xsd:string" use="required" />
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Anotacoes">
        <xsd:sequence>
            <xsd:element name="anotacao" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:complexContent>
                        <xsd:extension base="ValorTexto">
                            <xsd:attribute name="tipo" use="required">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="nota" />
                                        <xsd:enumeration value="referencia" />
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:attribute>
                        </xsd:extension>
                    </xsd:complexContent>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="pos" type="xsd:string" use="required" />
    </xsd:complexType>
</xsd:schema>

=== savioa/ipb-documentos/codigo_de_disciplina.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento titulo="Código de Disciplina da Igreja Presbiteriana do Brasil"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://savioa.github.io/ipb-documentos"
    xsi:schemaLocation="https://savioa.github.io/ipb-documentos documento.xsd">
    <preambulo>
        <texto>Em nome do Pai, e do Filho, e do Espírito Santo, nós, legítimos representantes da Igreja Presbiteriana do Brasil, reunidos em Supremo Concílio, no ano de 1951, investidos de toda a autoridade para cumprir as resoluções das legislaturas de 1946 e de 1950, com toda a confiança na bênção de Deus, nosso Pai, e visando exercer a justiça, manter a paz, sustentar a disciplina, preservar a unidade e promover a edificação da igreja de Cristo, decretamos e promulgamos, para glória de Deus Altíssimo, o seguinte Código de Disciplina.</texto>
    </preambulo>
    <capitulo id="1" titulo="Natureza e Finalidade">
        <secao id="1">
            <artigo id="1">
                <caput>
                    <texto>A igreja reconhece o foro íntimo da consciência, que escapa à sua jurisdição, e da qual só Deus é Juiz; mas reconhece também o foro externo que está sujeito à sua vigilância e observação.</texto>
                </caput>
            </artigo>
            <artigo id="2">
                <caput>
                    <texto>Disciplina eclesiástica é o exercício da jurisdição espiritual da igreja sobre seus membros, aplicada de acordo com a Palavra de Deus.</texto>
                </caput>
                <paragrafo id="1">
                    <texto>Toda disciplina visa edificar o povo de Deus, corrigir escândalos, erros ou faltas, promover a honra de Deus, a glória de Nosso Senhor Jesus Cristo e o próprio bem dos culpados.</texto>
                </paragrafo>
            </artigo>
            <artigo id="3">
                <caput>
                    <texto>Os membros não comungantes e outros menores, sob a guarda de pessoas crentes, recebem os cuidados espirituais da igreja, mas ficam sob a responsabilidade direta e imediata das referidas pessoas, que devem zelar por sua vida física, intelectual, moral e espiritual.</texto>
                </caput>
            </artigo>
        </secao>
    </capitulo>
    <capitulo id="2" titulo="Faltas">
        <secao id="1">
            <artigo id="4">
                <caput>
                    <texto>Falta é tudo que, na doutrina e prática dos membros e concílios da igreja, não esteja de conformidade com os ensinos da Sagrada Escritura, ou transgrida e prejudique a paz, a unidade, a pureza, a ordem e a boa administração da comunidade cristã.</texto>
                </caput>
                <paragrafo id="1">
                    <texto>Nenhum tribunal eclesiástico poderá considerar como falta, ou admitir como matéria de acusação aquilo que não possa ser provado como tal pela Escritura, segundo a interpretação dos Símbolos da Igreja (CI, <ref doc="ci">art. 1º</ref>).</texto>
                </paragrafo>
            </artigo>
            <artigo id="5">
                <caput>
                    <texto>A omissão dos deveres constantes do art. 3º constitui falta passível de pena.</texto>
                </caput>
            </artigo>
            <artigo id="6">
                <caput>
                    <texto>As faltas são de ação ou de omissão, isto é, a prática de atos pecaminosos ou a abstenção de deveres cristãos; ou, ainda, a situação ilícita.</texto>
                </caput>
                <paragrafo id="1">
                    <texto>As faltas são pessoais se atingem a indivíduos; gerais, se atingem a coletividade; públicas, se se fazem notórias; veladas, quando desconhecidas da comunidade.</texto>
                </paragrafo>
            </artigo>
            <artigo id="7">
                <caput>
                    <texto>Os concílios incidem em falta quando:</texto>
                    <alineas>
                        <alinea id="a">
                            <texto>tomam qualquer decisão doutrinária ou constitucional que flagrantemente aberra dos princípios fundamentais adotados pela igreja;</texto>
                        </alinea>
                        <alinea id="b">
                            <texto>procedem com evidente injustiça, desrespeitando disposição processual de importância, ou aplicando pena em manifesta desproporção com a falta;</texto>
                        </alinea>
                        <alinea id="c">
                            <texto>são deliberadamente contumazes, na desobediência às observações que, sem caráter disciplinar, o concílio superior fizer no exame periódico do livro de atas;</texto>
                        </alinea>
                        <alinea id="d">
                            <texto>tornam-se desidiosos no cumprimento de seus deveres, comprometendo o prestígio da igreja ou a boa ordem do trabalho;</texto>
                        </alinea>
                        <alinea id="e">
                            <texto>adotam qualquer medida comprometedora da paz, unidade, pureza e progresso da igreja.</texto>
                        </alinea>
                    </alineas>
                </caput>
            </artigo>
        </secao>
    </capitulo>
    <capitulo id="3" titulo="Penalidades">
        <secao id="1">
            <artigo id="8">
                <caput>
                    <texto>Não haverá pena, sem que haja sentença eclesiástica, proferida por um concílio competente, após processo regular.</texto>
                </caput>
            </artigo>
            <artigo id="9">
                <caput>
                    <texto>Os concílios só podem aplicar a pena de:</texto>
                    <alineas>
                        <alinea id="a">
                            <texto>admoestação, que consiste em chamar à ordem o culpado, verbalmente ou por escrito, de modo reservado, exortando-o a corrigir-se;</texto>
                        </alinea>
                        <alinea id="b">
                            <texto>afastamento, que em referência aos membros da igreja, consiste em serem impedidos de comunhão; em referência, porém, aos oficiais, consiste em serem impedidos do exercício do seu ofício e, se for o caso, da comunhão da igreja. O afastamento deve dar-se quando o crédito da religião, a honra de Cristo e o bem do faltoso o exigem, mesmo depois de ter dado satisfação ao tribunal. Aplica-se por tempo indeterminado, até o faltoso dar prova do seu arrependimento, ou até que a sua conduta mostre a necessidade de lhe ser imposta outra pena mais severa;</texto>
                        </alinea>
                        <alinea id="c">
                            <texto>exclusão, que consiste em eliminar o faltoso da comunhão da igreja. Esta pena só pode ser imposta quando o faltoso se mostra incorrigível e contumaz;</texto>
                        </alinea>
                        <alinea id="d">
                            <texto>deposição é a destituição de ministro, presbítero ou diácono de seu ofício.</texto>
                        </alinea>
                    </alineas>
                </caput>
            </artigo>
            <artigo id="10">
                <caput>
                    <texto>Os concílios superiores só podem aplicar aos inferiores as seguintes penas: repreensão, interdição e dissolução;</texto>
                    <alineas>
                        <alinea id="a">
                            <texto>repreensão é a reprovação formal de faltas ou irregularidades com ordem terminante de serem corrigidas;</texto>
                        </alinea>
                        <alinea id="b">
                            <texto>interdição é a pena que determina a privação temporária das atividades do concílio;</texto>
                        </alinea>
                        <alinea id="c">
                            <texto>dissolução é a pena que extingue o concílio.</texto>
                        </alinea>
                    </alineas>
                </caput>
                <paragrafo id="1">
                    <texto>Nos casos de interdição ou dissolução do Conselho ou Presbitério deverá haver recurso de ofício para o concílio imediatamente superior.</texto>
                </paragrafo>
                <paragrafo id="2">
                    <texto>As penas aplicadas a um concílio não atingem individualmente seus membros, cuja responsabilidade pessoal poderá ser apurada pelos concílios competentes.</texto>
                </paragrafo>
                <paragrafo id="3">
                    <texto>É facultado a qualquer dos membros do concílio interditado ou dissolvido recorrer da decisão para o concílio imediatamente superior àquele que proferiu a sentença.</texto>
                </paragrafo>
            </artigo>
            <artigo id="11">
                <caput>
                    <texto>Aplicadas as penas previstas nas alíneas “b” e “c” do artigo anterior, o concílio superior, por sua Comissão Executiva, tomará as necessárias providências para o prosseguimento dos trabalhos afetos ao concílio disciplinado.</texto>
                </caput>
            </artigo>
            <artigo id="12">
                <caput>
                    <texto>No julgamento dos concílios, devem ser observadas no que lhes for aplicável, as disposições gerais de processo adotadas nesta Constituição.</texto>
                </caput>
            </artigo>
            <artigo id="13">
                <caput>
                    <texto>As penas devem ser proporcionais às faltas, atendendo-se, não obstante, às circunstâncias atenuantes e agravantes, a juízo do tribunal, bem como à graduação estabelecida nos arts. 9º e 10.</texto>
                </caput>
                <paragrafo id="1">
                    <texto>São atenuantes:</texto>
                    <alineas>
                        <alinea id="a">
                            <texto>pouca experiência religiosa;</texto>
